version: '3.1'
services: 
  web: 
    build: .
    ports: 
      - "9001:9001"
    restart: always
    container_name: server
    depends_on: 
      - db
  db: 
    image: daocloud.io/library/mongo:3.4.8
    ports: 
      - "27017:27017"
    restart: always
    container_name: dataBase
  