version: '3.1'
services: 
  web: 
    build: .
    ports: 
      - "9001:9001"
    restart: always
    depends_on: 
      - db
  db: 
    image: mongo
    ports: 
      - "27017:27017"
    restart: always